version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  execution:
    restart: "${RESTART}"
    stop_grace_period: 3m
    build:
      context: ./besu
      dockerfile: ${BESU_DOCKERFILE}
      args:
        - BUILD_TARGET=${BESU_SRC_BUILD_TARGET}
        - DOCKER_TAG=${BESU_DOCKER_TAG}
    image: besu:local-merge
    #    user: besu
    user: root
    environment:
      - JAVA_OPTS=-Xmx4g
    volumes:
      - besuexecution-data:/var/lib/besu
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}-secrets:/secrets
    ports:
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/tcp
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/udp
    expose:
      - ${EL_RPC_PORT}/tcp
      - ${EL_WS_PORT}/tcp
      - 9545/tcp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - /opt/besu/bin/besu
      - --data-path
      - /var/lib/besu
      - --p2p-port
      - ${EL_P2P_PORT}
      - --rpc-http-enabled
      - --rpc-http-api
      - "WEB3,ETH,NET"
      - --rpc-http-host
      - 0.0.0.0
      - --rpc-http-port
      - ${EL_RPC_PORT}
      - --rpc-http-cors-origins=*
      - --rpc-ws-enabled
      - --rpc-ws-api
      - "WEB3,ETH,NET"
      - --rpc-ws-host
      - 0.0.0.0
      - --rpc-ws-port
      - ${EL_WS_PORT}
      - --host-allowlist=*
      - --engine-host-allowlist=*
      - --engine-jwt-enabled=true
      - --engine-jwt-secret=/var/lib/besu/jwtsecret
      - --engine-rpc-http-port=8551
      - --engine-rpc-ws-port=8551
      - --logging
      - ${LOG_LEVEL}
      - --metrics-enabled
      - --metrics-host
      - 0.0.0.0
      - --data-storage-format=BONSAI
      - --sync-mode=FULL
      - --network
      - ${NETWORK}
      - --Xmerge-support
      - "true"
  eth:
    depends_on:
      - execution
volumes:
  besuexecution-data:
