version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  execution:
    restart: "${RESTART}"
    build:
      context: ./geth
      dockerfile: ${GETH_DOCKERFILE}
      args:
        - BUILD_TARGET=${GETH_SRC_BUILD_TARGET}
        - DOCKER_TAG=${GETH_DOCKER_TAG}
    stop_grace_period: 3m
    image: geth:local-merge
    user: root
    volumes:
      - gethexecution-data:/var/lib/goethereum
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}-secrets:/secrets
    ports:
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/tcp
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/udp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - geth
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.api
      - web3,eth,net,engine
      - --datadir
      - /var/lib/goethereum
      - --port
      - ${EL_P2P_PORT}
      - --http.port
      - ${EL_RPC_PORT}
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${EL_WS_PORT}
      - --ws.api
      - web3,eth,net,engine
      - --metrics
      - --metrics.expensive
      - --pprof
      - --pprof.addr
      - 0.0.0.0
      - --bootnodes
      - ${ENODE}
      - --${NETWORK}
      - --authrpc.jwtsecret
      - /var/lib/goethereum/jwtsecret
      - --authrpc.addr
      - 0.0.0.0
      - --authrpc.vhosts=*
    command: ${GETH_CACHE}
  eth:
    depends_on:
      - execution
volumes:
  gethexecution-data:
