version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./lighthouse
      dockerfile: ${LH_DOCKERFILE}
      args:
        - BUILD_TARGET=${LH_SRC_BUILD_TARGET}
        - DOCKER_TAG=${LH_DOCKER_TAG}
    image: lighthouse:local-merge
    user: lhconsensus
    stop_grace_period: 1m
    volumes:
      - lhconsensus-data:/var/lib/lighthouse
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}-secrets:/secrets
    ports:
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/tcp
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/udp
    expose:
      - 5052/tcp
      - 5054/tcp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - lighthouse
      - bn
      - --disable-upnp
      - --datadir
      - /var/lib/lighthouse
      - --http
      - --http-address
      - 0.0.0.0
      - --http-port
      - "5052"
      - --enr-udp-port
      - ${CL_P2P_PORT}
      - --enr-tcp-port
      - ${CL_P2P_PORT}
      - --discovery-port
      - ${CL_P2P_PORT}
      - --target-peers
      - ${LH_PEER_COUNT}
      - --eth1-endpoints
      - ${EL_NODE}
      - --execution-endpoints
      - ${EL_NODE_EXECUTION}
      - --debug-level=${LOG_LEVEL}
      - --metrics
      - --metrics-address
      - 0.0.0.0
      - --validator-monitor-auto
      - --network
      - ${NETWORK}
      - --http-allow-sync-stalled
      - --jwt-secrets
      - /secrets/jwtsecret
      - --merge
      - --suggested-fee-recipient
      - ${REWARDS_TO}
  validator:
    restart: "${RESTART}"
    image: lighthouse:local-merge
    user: lhvalidator
    expose:
      - 5064/tcp
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint:
      - lighthouse
      - vc
      - --datadir
      - /var/lib/lighthouse
      - --init-slashing-protection
      - --beacon-nodes
      - ${CL_NODE}
      - --graffiti
      - ${GRAFFITI}
      - --debug-level=${LOG_LEVEL}
      - --metrics
      - --metrics-address
      - 0.0.0.0
      - --network
      - ${NETWORK}
      - --http
      - --http-port
      - ${KEY_API_PORT:-7500}
      - --http-address
      - 0.0.0.0
      - --http-allow-origin
      - "*"
      - --unencrypted-http-transport
    depends_on:
      - consensus
  get-keyapi-token:
    restart: "no"
    image: alpine:latest
    user: "10000"
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        cat /var/lib/lighthouse/validators/api-token.txt
        echo
  validator-import:
    restart: "no"
    image: lighthouse:local-merge
    user: root
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-''}
    entrypoint:
      - validator-import.sh
      - lighthouse
      - account
      - validator
      - import
      - --datadir
      - /var/lib/lighthouse
      - --directory
      - /val_keys
      - --network
      - ${NETWORK}
      - --debug-level=${LOG_LEVEL}
  validator-exit:
    restart: "no"
    image: lighthouse:local-merge
    user: root
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - validator-exit.sh
      - lighthouse
      - account
      - validator
      - exit
      - --beacon-node
      - http://consensus:5052
      - --datadir
      - /var/lib/lighthouse
      - --debug-level=${LOG_LEVEL}
      - --keystore
    depends_on:
      - consensus
  validator-account:
    restart: "no"
    image: lighthouse:local-merge
    user: lhvalidator
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - ${DEPCLI_LOCALDIR}:/interchange
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - lighthouse
      - account
      - validator
      - --datadir
      - /var/lib/lighthouse
      - --debug-level=${LOG_LEVEL}
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
      - validator
volumes:
  lhconsensus-data:
  lhvalidator-data:
