version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./lodestar
      dockerfile: ${LS_DOCKERFILE}
      args:
        - BUILD_TARGET=${LS_SRC_BUILD_TARGET}
        - DOCKER_TAG=${LS_DOCKER_TAG}
    image: lodestar:local-merge
    user: lsconsensus
    stop_grace_period: 1m
    volumes:
      - lsconsensus-data:/var/lib/lodestar/consensus
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
      - ./${NETWORK}-secrets:/secrets
    ports:
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/tcp
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/udp
    expose:
      - 5052/tcp
    <<: *logging
    entrypoint:
      - node
      - --max-old-space-size=6144
      - /usr/app/node_modules/.bin/lodestar
      - beacon
      - --rootDir
      - /var/lib/lodestar/consensus
      - --api.rest.enabled
      - "true"
      - --api.rest.host
      - 0.0.0.0
      - --api.rest.port
      - "5052"
      - --network.discv5.bindAddr
      - "/ip4/0.0.0.0/udp/${CL_P2P_PORT}"
      - --network.localMultiaddrs
      - "/ip4/0.0.0.0/tcp/${CL_P2P_PORT}"
      - --logLevel
      - ${LOG_LEVEL}
      - --paramsFile
      - /configs/config.yaml
      - --genesisStateFile
      - /configs/genesis.ssz
      - --network.discv5.bootEnrs
      - ${ENR}
      - --network.connectToDiscv5Bootnodes
      - --network.discv5.enabled=true
      - --eth1.providerUrls
      - ${EL_NODE}
      - --eth1.depositContractDeployBlock=0
      - --execution.urls=${EL_NODE_EXECUTION}
      - --jwt-secret=/secrets/jwtsecret
  validator:
    restart: "${RESTART}"
    image: lodestar:local-merge
    user: lsvalidator
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    <<: *logging
    entrypoint:
      - node
      - --max-old-space-size=8192
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - --rootDir
      - /var/lib/lodestar/validators
      - --server
      - http://consensus:5052
      - --graffiti
      - ${GRAFFITI}
      - --logLevel
      - ${LOG_LEVEL}
      - --paramsFile
      - /configs/config.yaml
  validator-import:
    restart: "${RESTART}"
    image: lodestar:local-merge
    user: root
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-''}
    entrypoint:
      - validator-import.sh
      - node
      - --max-old-space-size=8192
      - /usr/app/node_modules/.bin/lodestar
      - account
      - validator
      - import
      - --rootDir
      - /var/lib/lodestar/validators
      - --directory
      - /val_keys
  validator-exit:
    restart: "no"
    image: lodestar:local-merge
    user: lsvalidator
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    entrypoint:
      - node
      - --max-old-space-size=8192
      - /usr/app/node_modules/.bin/lodestar
      - account
      - validator
      - voluntary-exit
      - --rootDir
      - /var/lib/lodestar/validators
      - --server
      - http://consensus:5052
      -  --logLevel
      - ${LOG_LEVEL}
      - --paramsFile
      - /configs/config.yaml
  validator-account:
    restart: "no"
    image: lodestar:local-merge
    user: lsvalidator
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - node
      - --max-old-space-size=8192
      - /usr/app/node_modules/.bin/lodestar
      - account
      - validator
      - --rootDir
      - /var/lib/lodestar/validators
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
      - validator
volumes:
  lsconsensus-data:
  lsvalidator-data:
