version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./nimbus
      args:
        - BUILD_TARGET=${NIM_SRC_BUILD_TARGET}
        - DOCKER_TAG=${NIM_DOCKER_TAG}
      dockerfile: ${NIM_DOCKERFILE}
    image: nimbus:local-merge
    #user: user
    user: root
    stop_grace_period: 1m
    volumes:
      - nimbus-data:/var/lib/nimbus
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    expose:
      - 8008/tcp
    ports:
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/tcp
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/udp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --non-interactive
      - --status-bar=false
      - --tcp-port=${CL_P2P_PORT}
      - --udp-port=${CL_P2P_PORT}
      - --max-peers=${NIM_PEER_COUNT}
      - --web3-url=${EL_NODE_EXECUTION}
      - --graffiti=${GRAFFITI}
      - --log-level=${LOG_LEVEL}
      - --rest
      - --rest-address=0.0.0.0
      - --rest-port=5052
      - --num-threads=0
      - --enr-auto-update=false
      - --doppelganger-detection=false
      - --metrics
      - --metrics-port=8008
      - --metrics-address=0.0.0.0
      - --validator-monitor-auto
      - --network=/configs
      - --bootstrap-node=${ENR}
      - --terminal-total-difficulty-override=${TOTAL_TERMINAL_DIFFICULTY}
      - --keymanager
      - --keymanager-port=${KEY_API_PORT:-7500}
      - --keymanager-address=0.0.0.0
      - --keymanager-allow-origin=*
      - --keymanager-token-file=/var/lib/nimbus/api-token.txt
  get-keyapi-token:
    restart: "no"
    image: alpine:latest
    user: "10002"
    volumes:
      - nimbus-data:/var/lib/nimbus
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        cat /var/lib/nimbus/api-token.txt
  validator-import:
    restart: "no"
    image: nimbus:local
    user: root
    volumes:
      - nimbus-data:/var/lib/nimbus
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
    entrypoint:
      - validator-import.sh
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --network=/configs
      - deposits
      - import
      - /val_keys
  validator-exit:
    restart: "no"
    image: nimbus:local-merge
    user: user
    volumes:
      - nimbus-data:/var/lib/nimbus
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --log-level=${LOG_LEVEL}
      - deposits
      - exit
      - --rest-url=http://consensus:5052
      - --validator=
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
volumes:
  nimbus-data:
