version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  execution:
    restart: "${RESTART}"
    stop_grace_period: 3m
    build:
      context: ./nethermind
      dockerfile: ${NM_DOCKERFILE}
      args:
        - BUILD_TARGET=${NM_SRC_BUILD_TARGET}
        - DOCKER_TAG=${NM_DOCKER_TAG}
    image: nethermind:local-merge
    #    user: nethermind
    user: root
    volumes:
      - nmexecution-data:/var/lib/nethermind
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}-secrets:/secrets
    ports:
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/tcp
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/udp
    expose:
      - ${EL_RPC_PORT}/tcp
      - ${EL_WS_PORT}/tcp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - dotnet
      - /nethermind/Nethermind.Runner.dll
      - --datadir
      - /var/lib/nethermind
      - --Init.WebSocketsEnabled
      - "true"
      - --Network.DiscoveryPort
      - ${EL_P2P_PORT}
      - --Network.P2PPort
      - ${EL_P2P_PORT}
      - --JsonRpc.Enabled
      - "true"
      - --JsonRpc.EnabledModules
      - "Web3,Eth,Subscribe,Net,Engine"
      - --JsonRpc.Host
      - 0.0.0.0
      - --JsonRpc.Port
      - ${EL_RPC_PORT}
      - --JsonRpc.JwtSecretFile=/var/lib/nethermind/jwtsecret
      - --JsonRpc.AdditionalRpcUrls=http://0.0.0.0:8551|http;wss|engine;eth;net;web3;subscribe
      - --JsonRpc.WebSocketsPort
      - ${EL_WS_PORT}
      - --Sync.FastSync
      - "true"
      - --config
      - ${NETWORK}
      - --Sync.AncientBodiesBarrier
      - "1"
      - --Sync.AncientReceiptsBarrier
      - "1"
      - --Pruning.Mode
      - Full
      - --Pruning.FullPruningTrigger
      - VolumeFreeSpace
      - --Pruning.FullPruningMaxDegreeOfParallelism
      - "2"
  eth:
    depends_on:
      - execution
volumes:
  nmexecution-data:
