version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

x-build: &prysm-build
  context: ./prysm
  dockerfile: ${PRYSM_DOCKERFILE}
  args:
    - BUILD_TARGET=${PRYSM_SRC_BUILD_TARGET}
    - DOCKER_TAG=${PRYSM_DOCKER_TAG}

services:
  consensus:
    restart: "${RESTART}"
    build:
      target: consensus
      <<: *prysm-build
    image: prysm-consensus:local-merge
    user: prysmconsensus
    stop_grace_period: 1m
    volumes:
      - prysmconsensus-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
      - ./${NETWORK}-secrets:/secrets
    ports:
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/tcp
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/udp
    expose:
      - 4000/tcp
      - 5052/tcp
      - 8080/tcp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - beacon-chain
      - --datadir
      - /var/lib/prysm/
      - --rpc-host
      - 0.0.0.0
      - --grpc-gateway-host
      - 0.0.0.0
      - --grpc-gateway-port
      - "5052"
      - --http-web3provider
      - ${EL_NODE_EXECUTION}
      - --jwt-secret
      - /secrets/jwtsecret
      - --p2p-tcp-port
      - ${CL_P2P_PORT}
      - --p2p-udp-port
      - ${CL_P2P_PORT}
      - --p2p-max-peers
      - ${PRYSM_PEER_COUNT}
      - --verbosity
      - ${LOG_LEVEL}
      - --accept-terms-of-use
      - --monitoring-host
      - 0.0.0.0
      - --genesis-state
      - /configs/genesis.ssz
      - --chain-config-file
      - /configs/config.yaml
      - --bootstrap-node
      - ${ENR}
      - --suggested-fee-recipient
      - ${REWARDS_TO}
    labels:
      - traefik.enable=true
      - traefik.http.routers.cl.entrypoints=websecure
      - traefik.http.routers.cl.rule=Host(`${CL_HOST}.${DOMAIN}`)
      - traefik.http.routers.cl.service=cl
      - traefik.http.routers.cl.tls.certresolver=letsencrypt
      - traefik.http.services.cl.loadbalancer.server.port=5052
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
volumes:
  prysmconsensus-data:
