version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

x-build: &prysm-build
  context: ./prysm
  dockerfile: ${PRYSM_DOCKERFILE}
  args:
    - BUILD_TARGET=${PRYSM_SRC_BUILD_TARGET}
    - DOCKER_TAG=${PRYSM_DOCKER_TAG}
    - DOCKER_VC_TAG=${PRYSM_VC_DOCKER_TAG}

services:
  consensus:
    restart: "${RESTART}"
    build:
      target: consensus
      <<: *prysm-build
    image: prysm-consensus:local-merge
    user: prysmconsensus
    stop_grace_period: 1m
    volumes:
      - prysmconsensus-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
      - ./${NETWORK}-secrets:/secrets
    ports:
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/tcp
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/udp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - beacon-chain
      - --datadir
      - /var/lib/prysm/
      - --rpc-host
      - 0.0.0.0
      - --grpc-gateway-host
      - 0.0.0.0
      - --grpc-gateway-port
      - "5052"
      - --http-web3provider
      - ${EL_NODE_EXECUTION}
      - --jwt-secret
      - /secrets/jwtsecret
      - --p2p-tcp-port
      - ${CL_P2P_PORT}
      - --p2p-udp-port
      - ${CL_P2P_PORT}
      - --p2p-max-peers
      - ${PRYSM_PEER_COUNT}
      - --verbosity
      - ${LOG_LEVEL}
      - --accept-terms-of-use
      - --monitoring-host
      - 0.0.0.0
      - --genesis-state
      - /configs/genesis.ssz
      - --chain-config-file
      - /configs/config.yaml
      - --bootstrap-node
      - ${ENR}
      - --suggested-fee-recipient
      - ${REWARDS_TO}
  validator:
    restart: "${RESTART}"
    build:
      target: validator
      <<: *prysm-build
    image: prysm-validator:local-merge
    user: prysmvalidator
    expose:
      - 8081/tcp
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    <<: *logging
    entrypoint:
      - validator
      - --datadir
      - /var/lib/prysm
      - --wallet-dir
      - /var/lib/prysm/
      - --wallet-password-file
      - /var/lib/prysm/password.txt
      - --beacon-rpc-provider
      - consensus:4000
      - --graffiti
      - ${GRAFFITI}
      - --verbosity
      - ${LOG_LEVEL}
      - --accept-terms-of-use
      - --monitoring-host
      - 0.0.0.0
      - --web
      - --grpc-gateway-host
      - 0.0.0.0
      - --grpc-gateway-port
      - ${KEY_API_PORT:-7500}
      - --grpc-gateway-corsdomain=*
      - --beacon-rpc-gateway-provider
      - consensus:5052
      - --chain-config-file
      - /configs/config.yaml
    depends_on:
      - consensus
    labels:
      - traefik.enable=true
      - traefik.http.routers.prysm.service=prysm
      - traefik.http.routers.prysm.entrypoints=web,websecure
      - traefik.http.routers.prysm.rule=Host(`${PRYSM_HOST}.${DOMAIN}`)
      - traefik.http.routers.prysm.tls.certresolver=letsencrypt
      - traefik.http.services.prysm.loadbalancer.server.port=${KEY_API_PORT}
  create-wallet:
    restart: "no"
    image: prysm-validator:local-merge
    user: prysmvalidator
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    entrypoint: create-wallet.sh
  get-keyapi-token:
    restart: "no"
    image: alpine:latest
    user: "10000"
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        sed -n 2p /var/lib/prysm/auth-token
  validator-list:
    restart: "no"
    user: prysmvalidator
    image: prysm-validator:local-merge
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    entrypoint:
      - validator
      - --datadir
      - /var/lib/prysm
      - --verbosity
      - ${LOG_LEVEL}
      - accounts
      - list
      - --wallet-dir=/var/lib/prysm/
      - --wallet-password-file=/var/lib/prysm/password.txt
      - --chain-config-file
      - /configs/config.yaml
  validator-import:
    restart: "no"
    image: prysm-validator:local-merge
    user: root
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-''}
      - WALLET_PASSWORD=${WALLET_PASSWORD:-''}
    entrypoint:
      - validator-import.sh
      - validator
      - --verbosity
      - ${LOG_LEVEL}
      - --datadir
      - /var/lib/prysm
      - accounts
      - import
      - --wallet-dir=/var/lib/prysm/
      - --keys-dir=/val_keys
  validator-exit:
    restart: "no"
    user: prysmvalidator
    image: prysm-validator:local-merge
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    entrypoint:
      - validator
      - --verbosity
      - ${LOG_LEVEL}
      - --datadir
      - /var/lib/prysm
      - accounts
      - voluntary-exit
      - --wallet-dir=/var/lib/prysm/
      - --beacon-rpc-provider=consensus:4000
      - --wallet-password-file=/var/lib/prysm/password.txt
      - --chain-config-file
      - /configs/config.yaml
    depends_on:
      - consensus
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
      - validator
volumes:
  prysmconsensus-data:
  prysmvalidator-data:
